name: Deploy via runner local

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Acessar repositório
        uses: actions/checkout@v3

      - name: Rodar script docker-update.sh
        run: |
          cd /var/www/testeApiDocker
          ./docker-update.sh
